version: '3.7'
services:
  db:
    image: postgres:14.1
    volumes:
      - ./pg-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AZUL_TELEMETRY_DB_USERNAME}
      POSTGRES_PASSWORD: ${AZUL_TELEMETRY_DB_PASSWORD}
      POSTGRES_DB: ${AZUL_TELEMETRY_DB_DBNAME}
    ports:
      - '127.0.0.1:${AZUL_TELEMETRY_DB_PORT:-5432}:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - '127.0.0.1:${AZUL_TELEMETRY_PGADMIN_PORT:-5050}:80'
