version: '3.3'
services:
  agent:
    image: agent:latest
    restart: unless-stopped
    ports:
      - '${AZUL_TELEMETRY_AGENT_BACKEND_PORT:-8080}:8080'
    command: [ 'java', '-jar', 'agent.jar' ]
    depends_on:
      - db

  db:
    image: postgres:14.1
    volumes:
      - ./pg-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${AZUL_TELEMETRY_DB_USERNAME}
      POSTGRES_PASSWORD: ${AZUL_TELEMETRY_DB_PASSWORD}
      POSTGRES_DB: ${AZUL_TELEMETRY_DB_DBNAME}
    restart: unless-stopped
    ports:
      - '${AZUL_TELEMETRY_DB_PORT:-5432}:5432'